### ISSUE TITLE
[ext] Allow NULL value for GPS coordinates for instances where Timeout Error cannot be resolved

### ISSUE THREAD

**Issue by TNgidi** [disarm-dev/douma-app#459]
@onlyjsmith commented on [Thu Jul 19 2018](https://github.com/locational/_tickets/issues/283)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/88
In instances where users are not able to collect GPS points due to hardware issues, they should still be able to submit their form details. These would count in coverage calculations according to their location dropdown selection, but would naturally not appear on the map.

**Comment by onlyjsmith** [comment]
Ok - from today's CHAI call: they are removing this as a requirement, but we've agreed to go ahead and implement. This will be _very_ useful if mid-season, any users are having trouble with GPS coords - we can turn-off with a config change, and there won't be a major drop in data quality.

**Comment by Nicolaidavies** [comment]
The branch uses the property `location_coords_optional` from `instance_config.applets.irs_record_point`. 

@onlyjsmith any thoughts on naming?

Will need to update config-validation and config-editor when we decide on name.

**Comment by Nicolaidavies** [comment]
We now have two properties under `irs_record_point`:

- location_selection_required
- gps_coords_required


We need to update the configurations for all instances to include those two properties and make sure they are both set to `true` to maintain current behaviour.
