### ISSUE TITLE
[ext] cleanup Namibia plan

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-dev/douma-app#463]
@onlyjsmith commented on [Thu May 31 2018](https://github.com/locational/_tickets/issues/236)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/58
Combine smaller plans

**Comment by onlyjsmith** [comment]
Links to #464

**Comment by onlyjsmith** [comment]
@Nicolaidavies worth checking the original ticket for short discussion there.

**Comment by Nicolaidavies** [comment]
@onlyjsmith 

For removing the plans, can we do that together on a two-finger-typing-ssh-session?

When creating the 2018 plan, can we temporarily remove the planning restriction so we can select all the villages in one go?

**Comment by onlyjsmith** [comment]
```js
targets = __disarm_debug_cache.geodata.villages.features.map(f => {
	return {
		id: f.properties.uID,
		number_of_structures: f.properties.NumStructu,
		assigned_to_team_name: null,
	}
})
```

```
db.getCollection('plans').find({personalised_instance_id: 'by_hand', country: 'nam'})
```

**Comment by Nicolaidavies** [comment]
We need to create a new plan from the updated geodata once #464 has been closed.

**Comment by Nicolaidavies** [comment]
Done together with J.
