### ISSUE TITLE
[ext] update NAM geodata

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-dev/douma-app#464]
@onlyjsmith commented on [Thu May 31 2018](https://github.com/locational/_tickets/issues/237)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/57
Some new villages need to be added

**Comment by onlyjsmith** [comment]
Links to #463

**Comment by Nicolaidavies** [comment]
It looks mostly fine. 

The only problem is the `display_field_name` `mp_NAME` is not unique. This might cause problems with filtering in irs_monitor and selecting the right village in irs_record_point.

@onlyjsmith Would you like to proceed with the updating of geodata or hold of?

![Screen Shot 2018-07-26 at 10.47.34.png](https://images.zenhubusercontent.com/5a55ca014b5806bc2bc22780/1266c2ab-1f53-48ff-9ec7-63c28019dd7a)

**Comment by onlyjsmith** [comment]
Thanks for checking. Think we need to let Sameen know before we go ahead.

**Comment by onlyjsmith** [comment]
I’ll ask Sameen.

**Comment by Nicolaidavies** [comment]
Nam villages has been updated on staging and production. Location selection has also been regenerated.

**Comment by TNgidi** [comment]
According to an email from Sameen, this is ready to close![Spark - INBOX 2018-09-04 10-14-50.png](https://images.zenhubusercontent.com/5ae1e96d4b5806bc2bd0c510/90902e61-63ea-401b-8b97-68946e8177ac)
