### ISSUE TITLE
[core/deploy] login without requiring any config, then download+cache configuration

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-dev/douma-app#67]
currently requires a config for app to load.

**Comment by onlyjsmith** [comment]
### Steps:

- [x] boot without config
- [x] user logs in 
- [x] retrieve config (maybe select from list)
- [ ] dynamically add `VueRouter` routes - https://router.vuejs.org/en/api/router-instance.html#methods (`addRoutes` as children of router)
- [ ] dynamically add `Vuex` store - https://vuex.vuejs.org/en/modules.html#dynamic-module-registration
- [ ] start the instance/applet as a child of the shell
- [ ] not sure what happens on reload (i.e. is config persisted in IDB or localStorage?)

Relates to https://github.com/locational/douma-api/issues/38

**Comment by Nicolaidavies** [comment]
With the latest changes to the branch `feature/52-app-loads-without-config` the shell app loads and retrieves a list of configs. 

After selecting a config, it saves it locally and boots the app. You can have multiple instance_configs saved and switch between them. It all works offline.

**Comment by onlyjsmith** [comment]
Stale
