### ISSUE TITLE
[core] notify user that private browsing mode on Firefox doesn't work

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-dev/douma-app#77]
IndexedDB is not supported in private mode, so cannot use for testing - either by us or others

https://bugzilla.mozilla.org/show_bug.cgi?id=781982

Would be _very_ good to inform user if they're trying this - can we test for IndexedDB before we start using it? Are there any workarounds we can use for this?

**Comment by onlyjsmith** [comment]
@TNgidi Can you add this caveat to the help file under a section that says what devices are supported? Basically, you can use Firefox, but not in private browsing mode.

**Comment by TNgidi** [comment]
@onlyjsmith will do. Thanks
